version: '3'

services:
  postgredb:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${{secrets.POSTGRES_USERNAME}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
    ports:
      - "5433:5432"
