version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "apt-get update && apt-get install -y postgresql-client && pg_isready -U $POSTGRES_USERNAME -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
