Feature: Compare Tabular Data to XLSX file

  Scenario: Check if Tabular Data exist and compare with xlsx file (non-deliberately)
    When I compare the following tabular data to sheet "Result1" in xlsx file "src/main/resources/master.xlsx"
      | id | title                    | description                                                                                                                        | price | discountPercentage | rating | stock  | brand   | category    | thumbnail                                             | images                                                                                                                                                                                                                                            |
      | 2  | iPhone X                 | SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...                              | 899   | 17.94746           | 4.44   | 34     | Apple   | smartphone  | https://i.dummyjson.com/data/products/2/thumbnail.jpg | https://i.dummyjson.com/data/products/2/1.jpg, https://i.dummyjson.com/data/products/2/2.jpg, https://i.dummyjson.com/data/products/2/3.jpg, https://i.dummyjson.com/data/products/2/thumbnail.jpg                                                |
      | 1  | iPhone 9                 | An apple mobile which is nothing like apple                                                                                        | 549   | 12.96              | 4.69   | 94     | Apple   | smartphones | https://i.dummyjson.com/data/products/1/thumbnail.jpg | https://i.dummyjson.com/data/products/1/1.jpg, https://i.dummyjson.com/data/products/1/2.jpg, https://i.dummyjson.com/data/products/1/3.jpg, https://i.dummyjson.com/data/products/1/4.jpg, https://i.dummyjson.com/data/products/1/thumbnail.jpg |
      | 6  | MacBook Pro              | MacBook Pro 2021 with mini-LED display may launch between September, November                                                      | 1749  | 11.02              | 4.57   | 83     | Apple   | laptops     | https://i.dummyjson.com/data/products/6/thumbnail.png | https://i.dummyjson.com/data/products/6/1.png, https://i.dummyjson.com/data/products/6/2.jpg, https://i.dummyjson.com/data/products/6/3.png, https://i.dummyjson.com/data/products/6/4.jpg_png                                                    |
      | 4  | OPPOF19                  | OPPO F19 is officially announced on April 2021.                                                                                    | 280   | 17.91              | 4.3    | 123_op | OPPO    | smartphones | https://i.dummyjson.com/data/products/4/thumbnail.jpg | https://i.dummyjson.com/data/products/4/1.jpg, https://i.dummyjson.com/data/products/4/2.jpg, https://i.dummyjson.com/data/products/4/3.jpg, https://i.dummyjson.com/data/products/4/4.jpg, https://i.dummyjson.com/data/products/4/thumbnail.jpg |
      | 3  | Samsung Universe 9_thing | Samsung's new variant which goes beyond Galaxy to the Universe                                                                     | 1249  | 15.46              | 4.09   | 36     | Samsung | smartphones | https://i.dummyjson.com/data/products/3/thumbnail.jpg | https://i.dummyjson.com/data/products/3/1.jpg                                                                                                                                                                                                     |
      | 5  | Huawei P30               | Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. | 499   | 10.58              | 4.09   | 32     | Huawei  | smartphones | https://i.dummyjson.com/data/products/5/thumbnail.jpg | https://i.dummyjson.com/data/products/5/1.jpg, https://i.dummyjson.com/data/products/5/2.jpg, https://i.dummyjson.com/data/products/5/3.jpg                                                                                                       |


  Scenario: Check if Tabular Data exist and compare with xlsx file (deliberately)
    When I compare the following tabular data to sheet "Result1" in xlsx file "src/main/resources/master.xlsx" with unique key "id"
      | id | title                    | description                                                                                                                        | price | discountPercentage | rating | stock  | brand   | category    | thumbnail                                             | images                                                                                                                                                                                                                                            |
      | 2  | iPhone X                 | SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...                              | 899   | 17.94746           | 4.44   | 34     | Apple   | smartphone  | https://i.dummyjson.com/data/products/2/thumbnail.jpg | https://i.dummyjson.com/data/products/2/1.jpg, https://i.dummyjson.com/data/products/2/2.jpg, https://i.dummyjson.com/data/products/2/3.jpg, https://i.dummyjson.com/data/products/2/thumbnail.jpg                                                |
      | 1  | iPhone 9                 | An apple mobile which is nothing like apple                                                                                        | 549   | 12.96              | 4.69   | 94     | Apple   | smartphones | https://i.dummyjson.com/data/products/1/thumbnail.jpg | https://i.dummyjson.com/data/products/1/1.jpg, https://i.dummyjson.com/data/products/1/2.jpg, https://i.dummyjson.com/data/products/1/3.jpg, https://i.dummyjson.com/data/products/1/4.jpg, https://i.dummyjson.com/data/products/1/thumbnail.jpg |
      | 6  | MacBook Pro              | MacBook Pro 2021 with mini-LED display may launch between September, November                                                      | 1749  | 11.02              | 4.57   | 83     | Apple   | laptops     | https://i.dummyjson.com/data/products/6/thumbnail.png | https://i.dummyjson.com/data/products/6/1.png, https://i.dummyjson.com/data/products/6/2.jpg, https://i.dummyjson.com/data/products/6/3.png, https://i.dummyjson.com/data/products/6/4.jpg_png                                                    |
      | 4  | OPPOF19                  | OPPO F19 is officially announced on April 2021.                                                                                    | 280   | 17.91              | 4.3    | 123_op | OPPO    | smartphones | https://i.dummyjson.com/data/products/4/thumbnail.jpg | https://i.dummyjson.com/data/products/4/1.jpg, https://i.dummyjson.com/data/products/4/2.jpg, https://i.dummyjson.com/data/products/4/3.jpg, https://i.dummyjson.com/data/products/4/4.jpg, https://i.dummyjson.com/data/products/4/thumbnail.jpg |
      | 3  | Samsung Universe 9_thing | Samsung's new variant which goes beyond Galaxy to the Universe                                                                     | 1249  | 15.46              | 4.09   | 36     | Samsung | smartphones | https://i.dummyjson.com/data/products/3/thumbnail.jpg | https://i.dummyjson.com/data/products/3/1.jpg                                                                                                                                                                                                     |
      | 5  | Huawei P30               | Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK. | 499   | 10.58              | 4.09   | 32     | Huawei  | smartphones | https://i.dummyjson.com/data/products/5/thumbnail.jpg | https://i.dummyjson.com/data/products/5/1.jpg, https://i.dummyjson.com/data/products/5/2.jpg, https://i.dummyjson.com/data/products/5/3.jpg                                                                                                       |
